baseURL = "https://framorac.github.io"
languageCode = "es_CL"
title = "Francisco Mora"
theme = "cactus"
[params]
  colortheme = "dark" # dark, light, white, or classic
  description = "Bienvenido a mi sitio personal, soy un Ingeniero QA y desarrollador de software, partidario del software libre y autodidacta a casi tiempo completo. Escribo sobre tecnología, GNU/Linux, Python, Java y PHP."
  postsOnHomePage = 5
  rss = true
  tagsOverview = false

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Artículos"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
  name = "github"
  link = "https://github.com/framorac"

[[params.social]]
  name = "email"
  link = "fmorac@alumnos.duoc.cl" # no need for "mailto:" at the start

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/framorac"

[[params.social]]
  name = "mastodon"
  link = "https://mastodon.la/@framorac"
