baseURL = "https://www.franciscomora.cl"
languageCode = "es_CL"
title = "Francisco Mora"
theme = "cactus"
[params]
  colortheme = "dark" # dark, light, white, or classic
  description = "Bienvenido a mi sitio personal, soy un Ingeniero QA y desarrollador de software, partidario del software libre y autodidacta a casi tiempo completo. Escribo sobre desarrollo de software, sistemas operativos, software libre y open source."
  postsOnHomePage = 5
  rss = true
  tagsOverview = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Artículos"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
  name = "github"
  link = "https://github.com/framorac"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/channel/UCgKmCq-59D5r02jUB11IZKA"

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/framorac"

[[params.social]]
  name = "mastodon"
  link = "https://mastodon.la/@framorac"

[[params.social]]
  name = "rss"
  link = "https://framorac.github.io/index.xml"